#!/usr/bin/env bash
# Displays numbers from 1 to 100

cn=1

while (( cn <= 100 ))
do
    if (( cn % 3 == 0 )) && (( cn % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( cn % 3 == 0 ))
    then
        echo "Fizz"
    elif (( cn % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$num"
    fi
    (( cn++ ))
done
